name: Deploy Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          scope: '@billl'
      - run: yarn
      - run: yarn test
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: yarn release
      # - run: yarn publish
      #   env: 
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

