on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main
          monorepo-tags: true

  Build-And-Publish:
    runs-on: ubuntu-latest
    if: ${{ steps.release.outputs.releases_created }}
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn build
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          echo "@spotify-confidence:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
          yarn publish-if-missing
